### ISSUE TITLE
DSpot plugin error report

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/stamp-ide#26]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: STAMP Eclipse plugin for DSpot	1.0.0.201809201413
- **Execution Environment**: Windows 10
- **Reporter**: Lars Thomas Boye

#### Description
First attempt at running DSpot through Eclipse. Default config in the wizard dialog. Console output below. Note that DSpot is currently not working for me from the command line either: https://github.com/STAMP-project/dspot/issues/557

[WARN] 2018-09-26 09:24:37 AutomaticBuilderFactory - No automatic builder specified in configuration, going to default.
[INFO] 2018-09-26 09:24:37 AutomaticBuilderFactory - Default: provided Maven automatic builder.
[INFO] 2018-09-26 09:24:37 MavenAutomaticBuilder - run maven dependency:build-classpath -Dmdep.outputFile=target/dspot/classpath
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[INFO] 2018-09-26 09:24:40 AutomaticBuilderFactory - Selected Maven automatic builder.
[INFO] 2018-09-26 09:24:40 MavenAutomaticBuilder - run maven clean test -DskipTests dependency:build-classpath -Dmdep.outputFile=target/dspot/classpath
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: E:\Dev\tellu-github\tellulib\target\dspot\classpath (Systemet finner ikke angitt bane)
	at eu.stamp_project.automaticbuilder.MavenAutomaticBuilder.compile(MavenAutomaticBuilder.java:77)
	at eu.stamp_project.utils.Initializer.initialize(Initializer.java:20)
	at eu.stamp_project.dspot.DSpot.<init>(DSpot.java:88)
	at eu.stamp_project.Main.run(Main.java:57)
	at eu.stamp_project.Main.run(Main.java:91)
	at eu.stamp_project.Main.main(Main.java:42)
Caused by: java.io.FileNotFoundException: E:\Dev\tellu-github\tellulib\target\dspot\classpath (Systemet finner ikke angitt bane)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at eu.stamp_project.automaticbuilder.MavenAutomaticBuilder.compile(MavenAutomaticBuilder.java:74)
	... 5 more

**Comment by jesus-gorronogoitia** [comment]
Hi @ltboye 
This a DSpot issue, as you also mention it is not working for you in the CLI.
